/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Penjualan;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import Koneksi.connect;



/**
 *
 * @author ANDIKA RISKY FAIZATAMA
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    connect db;
    public Admin() {
        db = new connect();
        initComponents();
        setTransparan();
        showTable();
        new Thread(){
            public void run(){
            while (true) {            
            Calendar kal = new GregorianCalendar();
            int tahun = kal.get(Calendar.YEAR);
            int bulan = kal.get(Calendar.MONTH)+1;
            int hari = kal.get(Calendar.DAY_OF_MONTH);
            int jam = kal.get(Calendar.HOUR_OF_DAY);
            int menit = kal.get(Calendar.MINUTE);
            int detik = kal.get(Calendar.SECOND);
            
            String tanggal = hari+"/"+bulan+"/"+tahun;
            String waktu = jam+":"+menit+":"+detik;
            
            txttanggal.setText(tanggal);
            txtjam.setText(waktu);
            }
        }
        }.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JLabel();
        txtjam = new javax.swing.JLabel();
        txtbarcode = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtstok = new javax.swing.JFormattedTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnKasir = new javax.swing.JButton();
        btnmin = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbarang = new javax.swing.JTable();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SEARCH");
        jLabel2.setOpaque(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KODE BARANG");
        jLabel3.setOpaque(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 140, 30));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA BARANG");
        jLabel4.setOpaque(false);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 130, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STOK");
        jLabel5.setOpaque(false);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 90, 30));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("HARGA");
        jLabel6.setOpaque(false);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 90, 30));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 30));

        txttanggal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txttanggal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 140, 30));

        txtjam.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtjam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 140, 30));

        txtbarcode.setBackground(new java.awt.Color(255, 255, 255));
        txtbarcode.setForeground(new java.awt.Color(255, 255, 255));
        txtbarcode.setOpaque(false);
        getContentPane().add(txtbarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 280, 40));

        txtcari.setBackground(new java.awt.Color(255, 255, 255));
        txtcari.setForeground(new java.awt.Color(255, 255, 255));
        txtcari.setOpaque(false);
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariKeyTyped(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 40));

        txtnama.setBackground(new java.awt.Color(255, 255, 255));
        txtnama.setForeground(new java.awt.Color(255, 255, 255));
        txtnama.setOpaque(false);
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 280, 40));

        txtharga.setBackground(new java.awt.Color(255, 255, 255));
        txtharga.setForeground(new java.awt.Color(255, 255, 255));
        txtharga.setOpaque(false);
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaKeyTyped(evt);
            }
        });
        getContentPane().add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 280, 40));

        txtstok.setBackground(new java.awt.Color(255, 255, 255));
        txtstok.setForeground(new java.awt.Color(255, 255, 255));
        txtstok.setText("0");
        txtstok.setOpaque(false);
        txtstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstokKeyTyped(evt);
            }
        });
        getContentPane().add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        btnTambah.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.setContentAreaFilled(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 140, 40));

        btnHapus.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 140, 40));

        btnUbah.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UPDATE");
        btnUbah.setContentAreaFilled(false);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 140, 40));

        btnKasir.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnKasir.setForeground(new java.awt.Color(255, 255, 255));
        btnKasir.setText("Kasir");
        btnKasir.setContentAreaFilled(false);
        btnKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasirActionPerformed(evt);
            }
        });
        getContentPane().add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 130, 40));

        btnmin.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnmin.setForeground(new java.awt.Color(255, 255, 255));
        btnmin.setText("-1");
        btnmin.setContentAreaFilled(false);
        btnmin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminActionPerformed(evt);
            }
        });
        getContentPane().add(btnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 30, 30));

        btnplus.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnplus.setForeground(new java.awt.Color(255, 255, 255));
        btnplus.setText("+1");
        btnplus.setContentAreaFilled(false);
        btnplus.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        getContentPane().add(btnplus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 30, 30));

        jScrollPane2.setOpaque(false);

        tblbarang.setForeground(new java.awt.Color(255, 255, 255));
        tblbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Stok", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbarang.setGridColor(new java.awt.Color(255, 255, 255));
        tblbarang.setOpaque(false);
        tblbarang.setRowHeight(25);
        tblbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbarang);
        if (tblbarang.getColumnModel().getColumnCount() > 0) {
            tblbarang.getColumnModel().getColumn(0).setResizable(false);
            tblbarang.getColumnModel().getColumn(1).setResizable(false);
            tblbarang.getColumnModel().getColumn(2).setResizable(false);
            tblbarang.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 910, 380));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/n1.png"))); // NOI18N
        Background.setMinimumSize(new java.awt.Dimension(0, 0));
        Background.setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1400, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String barcode,nama,tanggal;
        int stok,harga;
        barcode = txtbarcode.getText();
        nama = txtnama.getText();
        tanggal = txttanggal.getText();
        stok = Integer.parseInt(txtstok.getText());
        harga = Integer.parseInt(txtharga.getText());
        
        db.insertDB(barcode,tanggal,nama,stok,harga);
        txtbarcode.setText("");
        txtnama.setText("");
        txtstok.setText("");
        txtharga.setText("");
        showTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminActionPerformed
        int total = Integer.parseInt(txtstok.getText()) - 1;
        txtstok.setText(String.valueOf(total));
        if(Integer.parseInt(txtstok.getText()) <= 0){
            txtstok.setText("0");
        }
    }//GEN-LAST:event_btnminActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        int total = Integer.parseInt(txtstok.getText()) + 1;
        txtstok.setText(String.valueOf(total));
        if(Integer.parseInt(txtstok.getText()) <= 0){
            txtstok.setText("0");
        }
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasirActionPerformed
        this.dispose();
        new Penjualan().setVisible(true);
    }//GEN-LAST:event_btnKasirActionPerformed

    private void tblbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbarangMouseClicked
        int row = tblbarang.getSelectedRow();
        txtbarcode.setText(tblbarang.getValueAt(row,0).toString());
        txtnama.setText(tblbarang.getValueAt(row,2).toString());
        txtstok.setText(tblbarang.getValueAt(row,3).toString());
        txtharga.setText(tblbarang.getValueAt(row,4).toString());
    }//GEN-LAST:event_tblbarangMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String barcode;
        barcode = txtbarcode.getText();
        db.deleteDB(barcode);
        showTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String barcode,nama,tanggal;
        int stok,harga;
        barcode = txtbarcode.getText();
        nama = txtnama.getText();
        tanggal = txttanggal.getText();
        stok = Integer.parseInt(txtstok.getText());
        harga = Integer.parseInt(txtharga.getText());
        db.updateDB(barcode,tanggal, nama, stok, harga);
        showTable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txtstokKeyTyped

    private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
        }
    }//GEN-LAST:event_txthargaKeyTyped

    private void txtcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyTyped
        DefaultTableModel model;
        model = new DefaultTableModel (new String[]{"Kode Barang","Tanggal","Nama Barang","Stok","harga"},0);
        try {
            ResultSet rs;
            rs = db.searchDB(txtcari.getText());
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("Barcode"),
                    rs.getString("tanggal"),
                    rs.getString("Nama"),
                    rs.getInt("Stok"),
                    rs.getInt("Harga")
                });
            }
        } catch (SQLException ex) {
            System.out.println("tidak menemukan"+ex);
        }
        tblbarang.setModel(model);
    }//GEN-LAST:event_txtcariKeyTyped

    private void showTable(){
        DefaultTableModel model;
        model = new DefaultTableModel (new String[]{"Kode Barang","Tanggal","Nama Barang","Stok","harga","Terjual"},0);
        try {
            //model = new DefaultTableModel (new String[]{"Kode Barang","Nama Barang","Stok","harga"},0);
            //DefaultTableModel model = (DefaultTableModel) tblbarang.getModel();
            ResultSet rs;
            rs = db.SelectDB();
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getString("Barcode"),
                    rs.getString("tanggal"),
                    rs.getString("Nama"),
                    rs.getInt("Stok"),
                    rs.getInt("Harga"),
                    rs.getInt("terjual")
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblbarang.setModel(model);
    }
    private void setTransparan(){
        tblbarang.setOpaque(false);
        ((DefaultTableCellRenderer) tblbarang.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKasir;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnmin;
    private javax.swing.JButton btnplus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblbarang;
    private javax.swing.JTextField txtbarcode;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JLabel txtjam;
    private javax.swing.JTextField txtnama;
    private javax.swing.JFormattedTextField txtstok;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
